name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  auto_route: ^11.1.0
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.0
  get_it: ^9.2.0
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  retrofit: ^4.5.0
  talker: ^5.1.9
  talker_bloc_logger: ^5.1.9
  talker_dio_logger: ^5.1.9
  talker_flutter: ^5.1.9
  talker_logger: ^5.1.9

dev_dependencies:
  auto_route_generator: ^10.2.3
  build: ^4.0.3
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5
  lean_builder: ^0.1.0-alpha.13
  retrofit_generator: ^10.2.1

flutter_launcher_icons:
  android: "lc_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#000000"
  image: "assets/icon/icon.png"
  branding: "assets/icon/icon.png"
  color_dark: "#121212"
  image_dark: "assets/icon/icon.png"
  branding_dark: "assets/icon/icon.png"

  android_12:
    color: "#000000"
    icon_background_color: "#ffffff"
    image: "assets/icon/icon.png"
    branding: "assets/icon/icon.png"

  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true

  assets:
    - '.env'

    - 'assets/svg/home.svg'
    - 'assets/svg/search.svg'
    - 'assets/svg/favorite.svg'
    - 'assets/svg/settings.svg'

    - 'assets/icon/icon.png'

  fonts:
    - family: Manrope
      fonts:
        - asset: 'assets/fonts/Manrope/Manrope-ExtraBold.ttf'
          weight: 800
        - asset: 'assets/fonts/Manrope/Manrope-Bold.ttf'
          weight: 700
        - asset: 'assets/fonts/Manrope/Manrope-SemiBold.ttf'
          weight: 600
        - asset: 'assets/fonts/Manrope/Manrope-Medium.ttf'
          weight: 500
        - asset: 'assets/fonts/Manrope/Manrope-Regular.ttf'
          weight: 400
        - asset: 'assets/fonts/Manrope/Manrope-Light.ttf'
          weight: 300
        - asset: 'assets/fonts/Manrope/Manrope-ExtraLight.ttf'
          weight: 200
