name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  auto_route: ^10.1.0+1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_lints: ^6.0.0
  build: ^2.5.4
  auto_route_generator: ^10.2.3
  lean_builder: ^0.1.0-alpha.13
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - '.env'

  fonts:
    - family: Manrope
      fonts:
        - asset: 'assets/fonts/Manrope/Manrope-ExtraBold.ttf'
          weight: 800
        - asset: 'assets/fonts/Manrope/Manrope-Bold.ttf'
          weight: 700
        - asset: 'assets/fonts/Manrope/Manrope-SemiBold.ttf'
          weight: 600
        - asset: 'assets/fonts/Manrope/Manrope-Medium.ttf'
          weight: 500
        - asset: 'assets/fonts/Manrope/Manrope-Regular.ttf'
          weight: 400
        - asset: 'assets/fonts/Manrope/Manrope-Light.ttf'
          weight: 300
        - asset: 'assets/fonts/Manrope/Manrope-ExtraLight.ttf'
          weight: 200
