name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - '.env'

  fonts:
    - family: Manrope
      fonts:
        - asset: 'assets/fonts/Manrope/Manrope-ExtraBold.ttf'
          weight: 800
        - asset: 'assets/fonts/Manrope/Manrope-Bold.ttf'
          weight: 700
        - asset: 'assets/fonts/Manrope/Manrope-SemiBold.ttf'
          weight: 600
        - asset: 'assets/fonts/Manrope/Manrope-Medium.ttf'
          weight: 500
        - asset: 'assets/fonts/Manrope/Manrope-Regular.ttf'
          weight: 400
        - asset: 'assets/fonts/Manrope/Manrope-Light.ttf'
          weight: 300
        - asset: 'assets/fonts/Manrope/Manrope-ExtraLight.ttf'
          weight: 200
