name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  auto_route: ^10.1.0+1
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  get_it: ^8.0.3
  talker: ^4.9.1
  talker_bloc_logger: ^4.9.1
  talker_dio_logger: ^4.9.1
  talker_flutter: ^4.9.1
  talker_logger: ^4.9.1

dev_dependencies:
  auto_route_generator: ^10.2.3
  build: ^2.5.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  lean_builder: ^0.1.0-alpha.13

flutter:
  uses-material-design: true

  assets:
    - '.env'

    - 'assets/svg/home.svg'
    - 'assets/svg/search.svg'
    - 'assets/svg/favorite.svg'
    - 'assets/svg/settings.svg'

  fonts:
    - family: Manrope
      fonts:
        - asset: 'assets/fonts/Manrope/Manrope-ExtraBold.ttf'
          weight: 800
        - asset: 'assets/fonts/Manrope/Manrope-Bold.ttf'
          weight: 700
        - asset: 'assets/fonts/Manrope/Manrope-SemiBold.ttf'
          weight: 600
        - asset: 'assets/fonts/Manrope/Manrope-Medium.ttf'
          weight: 500
        - asset: 'assets/fonts/Manrope/Manrope-Regular.ttf'
          weight: 400
        - asset: 'assets/fonts/Manrope/Manrope-Light.ttf'
          weight: 300
        - asset: 'assets/fonts/Manrope/Manrope-ExtraLight.ttf'
          weight: 200
